dist: xenial
language: python
python:
  - 3.6
services:
  - memcached
addons:
  postgresql: "9.6"

before_install:
  - pip install poetry
install:
  - poetry install

before_script:
  - psql -c "CREATE DATABASE perdiem;" -U postgres
  - cp .env-sample .env

script:
  - cd perdiem
  - poetry run python manage.py migrate
  - poetry run python manage.py collectstatic --no-input
  - poetry run coverage run ./manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
